In [1]:
import pandas as pd
import numpy as np

In [2]:
ba = pd.read_csv("ba_reviews.csv")
countries = pd.read_csv("Countries.csv")

In [3]:
ba.head()

,header,author,date,place,content,aircraft,traveller_type,seat_type,route,date_flown,recommended,trip_verified,rating,seat_comfort,cabin_staff_service,food_beverages,ground_service,value_for_money,entertainment
0,service was mediocre at best,Gary Storer,03/10/2023,United Kingdom,"Just returned from Chicago, flew out 10 days ...",A380,Couple Leisure,Economy Class,Chicago to Manchester via Heathrow,01/10/2023,no,Not Verified,2,2,3,1,2,2,-1
1,BA standards continue to decline,A Jensen,02/10/2023,United Kingdom,BA standards continue to decline every time ...,A320,Business,Business Class,London Heathrow to Munich,01/09/2023,no,Verified,2,2,1,2,1,1,-1
2,"won the race to the bottom""",John Rockett,02/10/2023,United Kingdom,Awful. Business class check in queue just as...,A320,Couple Leisure,Business Class,Heathrow to Istanbul,01/09/2023,no,Not Verified,2,2,3,2,1,1,-1
3,Not a reliable airline,Tatiana Bobrovskaya,02/10/2023,United Kingdom,Not a reliable airline. You cannot trust the...,A320,Business,Economy Class,London to Geneva,01/10/2023,no,Verified,3,4,4,2,1,1,-1
4,Very disappointed,Tom Slowbe,28/09/2023,United States,"The airplanes and the lounges are worn out, o...",777-300 and A320,Couple Leisure,First Class,Dallas to Dubrovnik via Heathrow,01/09/2023,no,Verified,1,1,4,4,3,2,3

In [4]:
ba.shape

(1324, 19)

In [5]:
ba.info()

<class 'pandas.DataFrame'>
RangeIndex: 1324 entries, 0 to 1323
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   header               1324 non-null   str
 1   author               1324 non-null   str
 2   date                 1324 non-null   str
 3   place                1324 non-null   str
 4   content              1324 non-null   str
 5   aircraft             1324 non-null   str
 6   traveller_type       1323 non-null   str
 7   seat_type            1324 non-null   str
 8   route                1324 non-null   str
 9   date_flown           1324 non-null   str
 10  recommended          1324 non-null   str
 11  trip_verified        1324 non-null   str
 12  rating               1324 non-null   int64
 13  seat_comfort         1324 non-null   int64
 14  cabin_staff_service  1324 non-null   int64
 15  food_beverages       1324 non-null   int64
 16  ground_service       1324 non-null   int64
 17  value_for_money      1324 non-null   int64
 18  entertainment        1324 non-null   int64
dtypes: int64(7), str(12)
memory usage: 196.7 KB

In [6]:
ba.describe(include='all')

,header,author,date,place,content,aircraft,traveller_type,seat_type,route,date_flown,recommended,trip_verified,rating,seat_comfort,cabin_staff_service,food_beverages,ground_service,value_for_money,entertainment
count,1324,1324,1324,1324,1324,1324,1323,1324,1324,1324,1324,1324,1324.000000,1324.000000,1324.000000,1324.000000,1324.000000,1324.000000,1324.000000
unique,1300,833,938,56,1324,150,4,4,836,88,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Overall a good flight,1 reviews,08/12/2019,United Kingdom,"Just returned from Chicago, flew out 10 days ...",A320,Couple Leisure,Economy Class,London to Johannesburg,01/04/2017,no,Verified,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,5,54,6,849,1,263,446,604,13,44,752,1215,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.188822,2.870091,3.280211,2.381420,3.031722,2.777946,1.435801
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.253325,1.386049,1.520592,1.697979,1.405815,1.409587,2.096598
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,1.000000,-1.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,2.000000,2.000000,1.000000,2.000000,1.000000,-1.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,3.000000,4.000000,2.000000,3.000000,3.000000,1.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,4.000000,5.000000,4.000000,4.000000,4.000000,3.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [7]:
ba.isnull().sum()

header                 0
author                 0
date                   0
place                  0
content                0
aircraft               0
traveller_type         1
seat_type              0
route                  0
date_flown             0
recommended            0
trip_verified          0
rating                 0
seat_comfort           0
cabin_staff_service    0
food_beverages         0
ground_service         0
value_for_money        0
entertainment          0
dtype: int64

In [8]:
ba.duplicated().sum()

np.int64(0)

In [12]:
for col in ba.select_dtypes(include=['object', 'string']):
    ba[col] = ba[col].str.strip()

In [13]:
ba["date"] = pd.to_datetime(ba["date"], dayfirst=True)
ba["date_flown"] = pd.to_datetime(ba["date_flown"], dayfirst=True)

In [15]:
ba["traveller_type"] = ba["traveller_type"].fillna("Unknown")

In [16]:
ba.isnull().sum()

header                 0
author                 0
date                   0
place                  0
content                0
aircraft               0
traveller_type         0
seat_type              0
route                  0
date_flown             0
recommended            0
trip_verified          0
rating                 0
seat_comfort           0
cabin_staff_service    0
food_beverages         0
ground_service         0
value_for_money        0
entertainment          0
dtype: int64

In [20]:
ba.to_csv("ba_reviews_cleaned.csv", index=False)